# Run bashrc if it exists
if [ -f ~/.bashrc ]; then 
  source ~/.bashrc 
fi
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
PATH="/usr/local/bin:$PATH"
PATH="/Users/kall004/Development/tools/homebrew/bin:$PATH"

